### ISSUE TITLE
Possible typo in bucket name

### ISSUE THREAD

**Issue by tisnik** [fabric8-analytics/f8a-stacks-report#27]
Please clarify if the `PYPI_MODEL_BUCKET` should really be set to `hpf-insights`:

https://github.com/fabric8-analytics/f8a-stacks-report/blob/33795db7de4a2bc7e77bc463765b897e82241ce5/f8a_report/report_helper.py#L111

**Comment by miteshvp** [comment]
@tisnik - that is correct. Its not a typo

**Comment by tisnik** [comment]
Thanks for clarification @miteshvp . Is it possible to make a comment into sources so everybody would know why are those two buckets the same, please?
